name: Build and Publish

on:
  push:
    branches: [ main ]
    paths-ignore:
#       - ".github/**"
      - "*.md"
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  monthly_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: e300nlp
        password: ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build & Push
      run: |
        cd dockerfile
        docker build -t=e300nlp/dev-env:cu10.1-py36-tf2.3.0-torch1.6.0-jupyter-vscode -f cu10.1-py36-tf2.3.0-torch1.6.0-jupyter-vscode .
        docker push e300nlp/dev-env:cu10.1-py36-tf2.3.0-torch1.6.0-jupyter-vscode
        docker image rm e300nlp/dev-env:cu10.1-py36-tf2.3.0-torch1.6.0-jupyter-vscode

        docker build -t=e300nlp/dev-env:cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode -f cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode .
        docker push e300nlp/dev-env:cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode
        docker image rm e300nlp/dev-env:cu10.1-py36-tf2.3.1-torch1.7.0-jupyter-vscode

        docker build -t=e300nlp/dev-env:py3.7.13-jupyter-vscode -f py3.7.13-jupyter-vscode .
        docker push e300nlp/dev-env:py3.7.13-jupyter-vscode
        docker image rm e300nlp/dev-env:py3.7.13-jupyter-vscode

        docker build -t=e300nlp/dev-env:py3.8.13-jupyter-vscode -f py3.8.13-jupyter-vscode .
        docker push e300nlp/dev-env:py3.8.13-jupyter-vscode
        docker image rm e300nlp/dev-env:py3.8.13-jupyter-vscode

        docker build -t=e300nlp/dev-env:py3.9.13-jupyter-vscode -f py3.9.13-jupyter-vscode .
        docker push e300nlp/dev-env:py3.9.13-jupyter-vscode
        docker image rm e300nlp/dev-env:py3.9.13-jupyter-vscode

        docker build -t=e300nlp/dev-env:cu113-py3.9.13-torch1.11.0-tf2.6.0-jupyter-vscode -f cu113-py3.9.13-torch1.11.0-tf2.6.0-jupyter-vscode .
        docker push e300nlp/dev-env:cu113-py3.9.13-torch1.11.0-tf2.6.0-jupyter-vscode
        docker image rm e300nlp/dev-env:cu113-py3.9.13-torch1.11.0-tf2.6.0-jupyter-vscode
    
    
